name: gogsgit
summary:  GOGS - A painless self-hosted Git service
#contact: https://github.com/tbraeutigam/gogs-snap/issues
description: |
  The goal of this project is to make the easiest, fastest, and most painless
  way of setting up a self-hosted Git service. With Go, this can be done with
  an independent binary distribution across ALL platforms that Go supports,
  including Linux, Mac OS X, Windows and ARM.

type: app
icon: snap/gogs.svg
confinement: strict
grade: stable

version: 'script'
version-script: |
  echo "$(cat stage/static/templates/.VERSION)+snap-$(git reflog | head -n1 | cut -d' ' -f1)"

apps:
  gogsgit:
    command: bin/gogs
    plugs: [network, network-bind]
  web:
    command: bin/gogs web
    daemon: simple
    plugs: [network, network-bind]
  admin:
    command: bin/gogs admin
    plugs: [network, network-bind]
  cert:
    command: bin/gogs cert
  hook:
    command: bin/gogs hook
    plugs: [network, network-bind]
  import:
    command: bin/gogs import
    plugs: [home]
  backup:
    command: bin/gogs backup
    plugs: [home]
  restore:
    command: bin/gogs restore
    plugs: [home]
  help:
    command: bin/gogs --help
  version:
    command: bin/gogs --version
  sqlite:
    command: usr/bin/sqlite3

parts:
  go:
    source-tag: go1.8.3
    prime:
      - -*

  gogs:
    plugin: nil
    source: https://github.com/gogits/gogs.git
    source-type: git
    source-tag: v0.11.29
    source-depth: 1
    after: [ go ]
    stage-packages: [ git, sqlite3, openssh-client ]
    build-packages: [ libpam0g-dev, libsqlite3-dev]
    prepare: |
      export PATH=$SNAPCRAFT_PART_INSTALL/../../go/install/bin:$PATH
      export GOPATH=$SNAPCRAFT_PART_INSTALL/../go
      export bld=$SNAPCRAFT_PART_INSTALL/../build
      export src=$SNAPCRAFT_PART_INSTALL/../src
      mkdir -p $GOPATH/src/github.com/gogits/gogs
      cp -r $src/* $GOPATH/src/github.com/gogits/gogs/
    build: |
      export PATH=$SNAPCRAFT_PART_INSTALL/../../go/install/bin:$PATH
      export GOPATH=$SNAPCRAFT_PART_INSTALL/../go
      cd $GOPATH/src/github.com/gogits/gogs
      go build -v -tags "sqlite pam cert"
    install: |
      # Set Convenience Variables
      src=$SNAPCRAFT_PART_INSTALL/../go/src/github.com/gogits/gogs
      # Copy build artifact and necessary files
      mkdir -p $SNAPCRAFT_PART_INSTALL/gogs/
      # Workaround for gogs ignoring APP_DATA_PATH in app.ini after snap update.
      ln -s /var/snap/$SNAPCRAFT_PROJECT_NAME/current/custom $SNAPCRAFT_PART_INSTALL/gogs/custom
      ln -s /var/snap/$SNAPCRAFT_PROJECT_NAME/common/data $SNAPCRAFT_PART_INSTALL/gogs/data
      # Workaround for cmd/certs not knowing how to put files somewhere else
      ln -s /var/snap/$SNAPCRAFT_PROJECT_NAME/current/cert.pem $SNAPCRAFT_PART_INSTALL/gogs/cert.pem
      ln -s /var/snap/$SNAPCRAFT_PROJECT_NAME/current/key.pem $SNAPCRAFT_PART_INSTALL/gogs/key.pem
      # Copy static content
      mkdir -p $SNAPCRAFT_PART_INSTALL/static
      cp    $SNAPCRAFT_PART_INSTALL/../go/src/github.com/gogits/gogs/gogs \
            $SNAPCRAFT_PART_INSTALL/gogs/
      cp -r $src/LICENSE \
            $src/templates \
            $src/public \
            $src/scripts \
            $SNAPCRAFT_PART_INSTALL/static/
      cp    $src/README.md $src/LICENSE \
            $SNAPCRAFT_PART_INSTALL/
    prime:
      - -etc
      - -usr/lib/systemd
      - -usr/lib/gcc
      - -usr/lib/sasl2
      - -usr/lib/x86_64-linux-gnu/krb5
      - -usr/share/apport
      - -usr/share/bash-completion
      - -usr/share/doc
      - -usr/share/git-core/contrib
      - -usr/share/man
      - -usr/share/upstart
      - -var

  helpers:
    plugin: dump
    source: snap/helpers
    organize:
      simple_launcher.sh: bin/gogs
      directorySetup.sh: bin/directorySetup.sh
      app.ini: gogs/snapApp.ini
